Repository: plone.restapi


Branch: refs/heads/master
Date: 2023-01-11T15:47:32+01:00
Author: Peter Mathis (petschki) <petschki@users.noreply.github.com>
Commit: https://github.com/plone/plone.restapi/commit/e7b1b54aa934aa63402d903cdb3481c140c45150

Testfix for changes in `zope.schema &gt;= 7.0.0` (#1568)

* Fix tests for `zope.schema &gt;= 7.0.0`

* changenote

* adjust testfix to work with zope.schema versions before and after 7.0.0

Files changed:
A news/1567.bugfix
M src/plone/restapi/tests/test_dxfield_deserializer.py

b'diff --git a/news/1567.bugfix b/news/1567.bugfix\nnew file mode 100644\nindex 000000000..704eaa488\n--- /dev/null\n+++ b/news/1567.bugfix\n@@ -0,0 +1,2 @@\n+Fix tests for `zope.schema >= 7.0.0`\n+[petschki]\ndiff --git a/src/plone/restapi/tests/test_dxfield_deserializer.py b/src/plone/restapi/tests/test_dxfield_deserializer.py\nindex 32b1ed3cf..d40f88c00 100644\n--- a/src/plone/restapi/tests/test_dxfield_deserializer.py\n+++ b/src/plone/restapi/tests/test_dxfield_deserializer.py\n@@ -487,7 +487,12 @@ def test_collection_deserializer_validates_value(self):\n         # DefaultFieldDeserializer that the CollectionFieldDeserializer will\n         # delegate to for deserializing collection items.\n         self.assertEqual("Object is of wrong type.", cm.exception.doc())\n-        self.assertEqual((b"2", (int,), ""), cm.exception.args)\n+        exception_args = list(cm.exception.args)\n+        if isinstance(exception_args[1], tuple):\n+            # BBB: since zope.schema >= 7.0.0 the Int field changed its validation `_type`\n+            # from (int, ) to int ... we adjust that to work with both versions\n+            exception_args[1] = exception_args[1][0]\n+        self.assertEqual([b"2", int, ""], exception_args)\n \n     def test_dict_deserializer_validates_value(self):\n         with self.assertRaises(ValidationError) as cm:\n'

