Repository: Products.CMFPlone


Branch: refs/heads/master
Date: 2016-12-28T16:47:40+01:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/Products.CMFPlone/commit/827d8ebff02b4aa5d96f0a03bda06ddf8581c7d6

TestAttackVectorsFunctional test_widget_traversal_2 assumed a 302 http return code when accessing some private API. Meanwhile it changed to return a 404 on the URL.

Files changed:
M CHANGES.rst
M Products/CMFPlone/tests/testSecurity.py

diff --git a/CHANGES.rst b/CHANGES.rst
index a37a492..55621b74 100644
--- a/CHANGES.rst
+++ b/CHANGES.rst
@@ -241,6 +241,13 @@ Bug fixes:
 - Do not use unittest2 (superfluos since part of Python 2.7).
   [jensens]
 
+- Fix security test assertion: 
+  TestAttackVectorsFunctional test_widget_traversal_2 assumed a 302 http return code when accessing some private API.
+  Meanwhile it changed to return a 404 on the URL. 
+  Reflect this in the test and expect a 404.
+  [jensens]
+
+
 5.1a2 (2016-08-19)
 ------------------
 
diff --git a/Products/CMFPlone/tests/testSecurity.py b/Products/CMFPlone/tests/testSecurity.py
index c2268b4..5dc8b81 100644
--- a/Products/CMFPlone/tests/testSecurity.py
+++ b/Products/CMFPlone/tests/testSecurity.py
@@ -72,7 +72,7 @@ def test_widget_traversal_1(self):
     def test_widget_traversal_2(self):
         res = self.publish(
             '/plone/@@discussion-settings/++widget++captcha/terms/field/interface/setTaggedValue?tag=cake&value=lovely')
-        self.assertEqual(302, res.status)
+        self.assertEqual(404, res.status)
         self.assertTrue(res.headers['location'].startswith(
             'http://nohost/plone/acl_users/credentials_cookie_auth/require_login'))
 


